import "./globals.css";

import type { Metadata } from "next";
import { ReactNode } from "react";
import RecoilRoot from "../components/RecoilRoot";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: []
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <RecoilRoot>
        <body>{children}</body>
      </RecoilRoot>
    </html>
  );
}
